export default {
  SET_TODO_TASK_LIST: "SET_TODO_TASK_LIST",
  ADD_NEW_ROOT_TASK: "ADD_NEW_ROOT_TASK",
  DELETE_TODO_TASK: "DELETE_TODO_TASK",
  STATUS_CHANGE_TODO: "STATUS_CHANGE_TODO",
  TASK_FAILED_TO_MODIFY: "TASK_FAILED_TO_MODIFY",
  SHOW_ALERT: "SHOW_ALERT",
  HIDE_ALERT: "HIDE_ALERT",
  SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
  REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION"
};
